Nitrokey/nitrokey-3-firmware

README.md

Here is a suggestion for a strategy to keep track of our modifications to the solo2 monorepo until it is split up into the separate components.
If you agree with the outlined strategy, we should also change the default branch for this repository to `nitrokey-main`.
cc @kliment @LennardBoediger

Document Nitrokey fork usage

---

README.md
nk3-quickstart.md

This patch adds a guide describing the necessary steps for compiling,
flashing and debugging the firmware for the Nitrokey 3 prototypes.
Also describes the changes proposed in #2.

Add Nitrokey 3 quickstart guide

---

Makefile
runners/lpc55/.gitignore
runners/lpc55/Cargo.toml
runners/lpc55/Makefile
runners/lpc55/board/Cargo.toml
runners/lpc55/board/README.md
runners/lpc55/board/src/lib.rs
runners/lpc55/board/src/nk3xn.rs
runners/lpc55/board/src/nk3xn/button.rs
runners/lpc55/board/src/nk3xn/led.rs
runners/lpc55/src/lib.rs

This patch adds support for the NK3 protypes.  board-nk3xn can be used
for the NK3AN (= USB A NFC) and the NK3CN (= USB C NFC), and board-nk3am
can be used for the NK3AM (= USB A Mini).  Currently, board-nk3am is
only an alias for the board-solo2 feature as the solo2 code also works
for the NK3AM.
It also makes it easier to select a board when using the Makefile by
adding the BOARD variable, defaulting to nk3xn.

Add board-nk3xn and board-nk3am features

---

components/admin-app/src/admin.rs
runners/lpc55/CHANGELOG.md

Previously, the CTAPHID interface of the admin app did not handle the
UUID command and interpreted all unknown commands as Wink commands.
With this patch, we explicitly handle both the Wink and the UUID command
and return an error if any other command is received.
Fixes #8.

Fix CTAPHID command dispatch for admin app

---

runners/lpc55/CHANGELOG.md
runners/lpc55/Cargo.lock
runners/lpc55/Cargo.toml

This patch updates the ctap-types and fido-authenticator dependencies to
add support for the pin protocl field in the hmac-secret extension data
so that the authenticatorGetAssertion command works with newer clients.
Fixes #14.
This is a draft as it requires changes to the fido-authenticator (https://github.com/solokeys/fido-authenticator/pull/1) and ctap-types (https://github.com/solokeys/ctap-types/pull/2) dependencies.  We can either wait for upstream to merge our changes or use forks instead.

Update ctap-types and fido-authenticator

---

runners/lpc55/CHANGELOG.md
runners/lpc55/board/src/trussed.rs

Previously, the wink command did not have any effect.  With this patch,
we toggle the LED between blue and green if the wink command has been
executed.  The LED blinks until the specified duration (currently 10
seconds) is over or the UI status is changed.
This requires a patched trussed version for this change:
https://github.com/trussed-dev/trussed/pull/15
Fix #9.

admin-app: Fix wink command

---

runners/lpc55/CHANGELOG.md
runners/lpc55/board/src/trussed.rs
runners/lpc55/src/initializer.rs

With this patch, we change the idle LED color from green to white and
append a " (provisioner)" suffix to the device name returned in the USB
descriptor if the provisioner app is enabled.  This makes it easier to
track the status of the provisioning process both optically and
programatically.

Change LED color and device name for provisioner

---

docs/quickstart.md

This patch updates the quickstart guide with the changes from
<https://github.com/Nitrokey/nitrokey-3-firmware/pull/6>.

Update quickstart guide

---

runners/lpc55/Cargo.lock

This patch updates the p256-cortex-m4 dependency to version
0.1.0-alpha.6.  This version includes a fix for signatures that are not
exactly 72 bytes long, see https://github.com/ycrypto/p256-cortex-m4/pull/4.
Fixes https://github.com/Nitrokey/nitrokey-3-firmware/issues/31

Update p256-cortex-m4 to 0.1.0-alpha.6

---

CHANGELOG.md
runners/lpc55/board/src/lib.rs
runners/lpc55/board/src/trussed.rs
runners/lpc55/board/src/ui.rs

This PR moves the LED handling to a new module and separates the UI state and the derived LED settings so that it is easier to consistently change the LED patterns.  Then it changes the LED patterns so that it is off by default and blinks green during a user confirmation request.
Note that I used green blinking instead of white because we already use white blinking for winking, but this is of course open to discussion.  This PR introduces a slight overhead of additional `uptime()` calls but this should be negligible.

Change LED patterns

---

CHANGELOG.md
runners/lpc55/board/src/trussed.rs
runners/lpc55/board/src/ui.rs

Previously, we removed the constant LED light.  To make it clearer when
the NK3 is powered, this patch adds a single white LED blink for 0.5
seconds after startup.  This is consistent with the FIDO2 behavior.

Add white LED blink after startup

---

CHANGELOG.md

According to our tests, retrieval of OpenSSH resident keys is now
working, see #48, so this patch adds this improvement to the changelog.

Document that OpenSSH key retrieval is working

---

CHANGELOG.md
runners/lpc55/board/src/ui.rs

For consistency with the Nitrokey FIDO2 behavior, we change the LED
color for winking to white (instead of blue).

Change LED color for winking to white

---

CHANGELOG.md
runners/lpc55/Cargo.lock
runners/lpc55/Cargo.toml
runners/lpc55/board/src/lib.rs
runners/lpc55/board/src/lpcxpresso55/led.rs
runners/lpc55/board/src/nk3xn/led.rs
runners/lpc55/board/src/solo2/led.rs
runners/lpc55/src/lib.rs

This patch replaces panic-halt with a custom panic handler that shows a
log message (if logging is enabled) and sets the LED to red.
For simplicity, I’m always resetting the LED pins to regular output pins (instead of PWM) and just set them to low or high.  This works in my test cases both before and after PWM is initialized, so I think this should be fine.
@szszszsz Can you re-run the test suite from https://github.com/Nitrokey/nitrokey-3-firmware/issues/49 with this patch and see if the indicator is working as expected?  I was only able to test this with panics that I caused artificially.
@daringer I think it should be possible to integrate this quite easily into the embedded runner and adapt it for nrf52.  Might also make sense to have this in place for the beta tests.  What do you …

Add custom panic handler

---

CHANGELOG.md
runners/lpc55/Cargo.lock
runners/lpc55/Cargo.toml
runners/lpc55/config/commands.bd

This release adds support for the NRF52 MCU, changes the LED color to
red on panics and allows the user to skip the additional user presence
check for the first FIDO2 operation within two seconds after boot.

Release v1.1.0

---

README.md
docs/identifiers.md

This patch adds a document that lists all identifiers used by the
firmware, currently:
- USB vendor and product ID
- FIDO2 AAGUID
- FIDO2 attestation certificate hashes

Add document with used identifiers

---

components/usbd-ccid/src/class.rs
components/usbd-ccid/src/pipe.rs
runners/embedded/src/types/usbnfc.rs
runners/lpc55/src/types/usb.rs

Similar to the usb-ctaphid implementation, we don’t need to require a
static lifetime for usb-ccid.  This makes it easier to use it e. g. in
a usbip runner.

usbd-ccid: Support non-static lifetimes

---

runners/lpc55/Cargo.toml
runners/lpc55/rust-toolchain.toml
rust-toolchain.toml

This PR removes the MSRV from `Cargo.toml` (as we always use latest stable), moves the `rust-toolchain.toml` to the root (so that it applies for all components and runners) and updates the specified Rust toolchain version to the latest stable, 1.62.1.

Update toolchain to Rust 1.62.1

---

README.md
docs/index.md
docs/lpc55-quickstart.md
docs/maintenance.md

This patch updates the documentation because we now support two chips,
LPC55 and NRF52.

Update documentation after nrf52 merge

---

runners/lpc55/src/lib.rs

The lpc55 runner had build warnings due to unused imports if the
provisioner features is not active.  This patch refactors the
provisioner initialization to fix these warnings.

Fix build warnings for lpc55 runner

---

CHANGELOG.md
runners/embedded/Cargo.lock
runners/embedded/Cargo.toml
runners/lpc55/Cargo.lock
runners/lpc55/Cargo.toml

This patch updates fido-authenticator to 4022d6c from our fork.  This
version returns an error instead of panicking if the credential ID is
too long.
Fixes: https://github.com/Nitrokey/nitrokey-3-firmware/issues/49

fido-authenticator: Update to 4022d6c

---

runners/embedded/Cargo.lock
runners/embedded/Cargo.toml
runners/embedded/src/types.rs
runners/lpc55/Cargo.lock
runners/lpc55/Cargo.toml
runners/lpc55/src/types.rs

This patch removes the piv-authenticator app from the lpc55 and embedded
runners.  We are not using it at the moment, and it pulls in a Git
version of trussed, leading to unnecessary dependency duplications.
Fixes: https://github.com/Nitrokey/nitrokey-3-firmware/issues/80

Remove piv-authenticator from runners

---

.gitlab-ci.yml

This PR updates the LPC55 CI builds:
- remove binaries for NK3AM as not used at the moment
- rename binaries to include the version number
- remove `artifacts` prefix from `sha256sum` as all files are placed in the same directory

Update LPC55 CI builds

---

CHANGELOG.md
components/usbd-ccid/src/pipe.rs

Previously, we just panicked when receiving an abort request.  This
caused a long delay in scdaemon/gnupg when the NK3 was connected.  With
this patch, we add abort handling to usb-ccid to fix this issue.
The implementation is based on Section 5.3.1 of the CCID specification
[0].  The device is expected to send two abort messages, one over the
bulk endpoint and one over the control pipe.  We perform the abort once
we have received both messages.  In the time between receiving the first
and the second message, we reject all incoming messages on the bulk
endpoint.
Fixes https://github.com/Nitrokey/nitrokey-3-firmware/issues/22
[0] https://www.usb.org/sites/default/files/DWG_Smart-Card_CCID_Rev110.pdf

usb-ccid: Implement abort handling

---

runners/embedded/Cargo.toml
runners/lpc55/Cargo.toml

* it was `0.1` should be `0.1.1` after removing the patch from the Nitrokey github repository
* `ssh-keygen` (output) errors occur w/o this and probably other issues

fix incorrect version for fido-authenticator

---

runners/embedded/Cargo.lock
runners/embedded/src/soc_nrf52840/mod.rs
runners/embedded/src/soc_nrf52840/types.rs
runners/embedded/src/types.rs

... and tiny newline cargo fmt fix

Enable locked-state (APPROTECT) read-out for nRF52

---

runners/lpc55/src/initializer.rs
runners/lpc55/src/lib.rs

This patch adds a basic sanity check for the SE050 chip to the LPC55 runner if the provisioner app is enabled.  This is based on the existing check for NRF52 in the embedded runner.

lpc55: Add SE050 hardware check

---

runners/lpc55/Cargo.lock
runners/lpc55/Cargo.toml
runners/lpc55/board/src/lib.rs
runners/lpc55/board/src/nfc.rs
runners/lpc55/board/src/spi.rs
runners/lpc55/src/initializer.rs
runners/lpc55/src/types.rs

This patch adds a check that verifies that the external flash storage can be accessed and formatted with a littlefs2 filesystem.

lpc55: Add external flash check

---

.gitlab-ci.yml
runners/embedded/Cargo.lock
runners/embedded/Cargo.toml
runners/embedded/Makefile
runners/embedded/src/soc_lpc55/init.rs
runners/embedded/src/soc_nrf52840/mod.rs
runners/embedded/src/types.rs

This is the first step in the alpha release setup.  It adds a `alpha` feature that triggers the nightly compiler and is also built in the CI.  For easier integration, it only includes `opcard` v0.1.0.  I will open a separate PR for the `opcard` integration.

Add alpha feature to embedded runner

---

.gitlab-ci.yml
runners/embedded/Cargo.lock
runners/embedded/Cargo.toml
runners/embedded/Makefile
runners/embedded/src/bin/app-lpc.rs
runners/embedded/src/bin/app-nrf.rs
runners/embedded/src/lib.rs
runners/embedded/src/soc_lpc55/init.rs
runners/embedded/src/soc_lpc55/monotonic.rs
runners/embedded/src/soc_nrf52840/mod.rs
runners/embedded/src/types.rs
utils/nrf-builder/Makefile

Update opcard to v0.2.0, oath-authenticator to v0.3.0 in alpha

---

.gitlab-ci.yml
runners/embedded/src/types.rs

* bumped opcard version (inside its init options)
* remove develop builds from the ci artifacts
* add version string to nrf build-artifacts

Release v1.2.2 alpha - opcard 0.2.0 oath 0.3.0

---

runners/embedded/Cargo.lock
runners/embedded/Cargo.toml

This patch adds tags for all forked Git dependencies used in the embedded runner.  This makes sure that revisions are not lost by force pushes.  It is also easier to interpret tags than revision hashes.
----
This fixes the CI that was broken due to a force push to trussed.

embedded: Use tags for forked Git dependencies

---

.gitlab-ci.yml
runners/embedded/ld/lpc55-memory-template.x
runners/embedded/src/soc_lpc55/init.rs

* includes #113
* avoid inlining init stages for lpc55
* zip resulting raw binaries to reduce clutter in release

Release v1.2.2-alpha.20221125

---

runners/embedded/Cargo.lock
runners/embedded/Cargo.toml

Instead of using nrf52840-hal as a Git dependency, use the published 0.15.1 version.
Fixes #103

embedded: Use nrf52840-hal 0.15.1

---

runners/embedded/Cargo.lock
runners/embedded/Cargo.toml

This patch updates trussed to revert postcard to 0.7.3.  This fixes an issue with decoding existing FIDO2 credentials.

embedded: Update trussed and revert postcard

---

Cargo.toml

This fixes a compiler error for the lpc55 runner.

Explicitly exclude lpc55 from workspace

---

runners/embedded/Cargo.toml
runners/embedded/src/soc_lpc55/init.rs
runners/embedded/src/soc_lpc55/spi.rs

This patch re-enables the lpc55 hardware checks in the provisioner and disables NFC if the hardware checks are executed to avoid communication issues linked to different SPI configurations for the external flash and the NFC chip.

embedded: Fix provisioner hardware checks for lpc55

---

components/apps/src/lib.rs

We forgot to enable the `button_available` option.

App opcard button support

---

runners/embedded/Makefile

cargo check runs significantly faster than cargo build because it can skip the expensive linking step.  This patch adds check and check-all targets to the Makefile that can be used during development to check for compilation issues.

embedded: Add check and check-all target to Makefile

---

runners/usbip/src/main.rs

This isn't really necessary, but it's in my opinion more readable since it moves the printing logic to another function, which makes it easier to read the `main()` function.

moving logic out of main

---

.gitlab-ci.yml
Makefile
runners/usbip/Makefile

This PR cleans up some Makefiles, adds a `lint` target to run `rustfmt` and a CI job to execute `make lint`.  The target name is based on our discussion in https://github.com/Nitrokey/nitrokey-3-firmware/pull/144.

Add lint target and CI job

---

runners/embedded/src/runtime.rs

The previous implementation is very likely UB, or could become UB easily: we would just need to use the methods in 2 different tasks for it to be UB.

Replace mutable static with atomic

---

Cargo.lock
components/apps/Cargo.toml
components/apps/src/lib.rs
components/usbd-ccid/Cargo.toml
components/usbd-ccid/src/class.rs
components/usbd-ccid/src/constants.rs
components/usbd-ccid/src/lib.rs
components/usbd-ccid/src/pipe.rs
components/usbd-ccid/src/types/packet.rs
runners/embedded/Cargo.toml
runners/usbip/Cargo.toml

This PR cleans up `usbd-ccid` a bit and adds the CCID apps (opcard) to the usbip runner.
Closes #140, #150 and #151
On my machine I enconter 2 bugs:
- `pcscd` and this somehow manage to trigger a kernel bug:
1. `cargo run --release --features alpha
2.  `usbip attach -r localhost -b 1-1` (enough times for it to not return immediately)
3. `opgpcard status` 
4. now `lsusb`  hangs and `dmesg` shows an error: `kernel BUG at mm/usercopy.c:101!`
- `gpg` still fails to detect this as an openpgp smartcard for some reason

Add ccid apps to the usbip runner

---

Cargo.lock
Cargo.toml
components/utils/Cargo.toml
components/utils/src/lib.rs
components/utils/src/storage.rs
runners/embedded/Cargo.toml
runners/embedded/src/bin/app-nrf.rs
runners/embedded/src/flash.rs
runners/embedded/src/lib.rs
runners/embedded/src/soc_lpc55/init.rs
runners/embedded/src/soc_lpc55/spi.rs
runners/embedded/src/soc_lpc55/types.rs
runners/usbip/Cargo.toml
runners/usbip/src/main.rs
runners/usbip/src/store.rs

This patch changes the external storage for the lpc55 SoC in the embedded runner to the external flash unless the device is in passive NFC mode.  In this case, 1024 bytes of RAM are used to simulate the external flash.
TODO:

embedded/lpc55: Use external flash in USB mode

---

docs/storage.md
runners/embedded/src/flash.rs
runners/embedded/src/soc_nrf52840/flash.rs
runners/embedded/src/soc_nrf52840/qspiflash.rs

The external flash now has a reserved portion at the end of the flash. 128kb (32 blocks) are left out at the end. 
This is done by using a reduced `BLOCK_COUNT`, which will restrict littlefs2 to the given `BLOCK_COUNT`, but the low-level `read`/`write`/`erase` methods for `ExtFlashStorage` will still accept operations on this region.

ExtFlash: update layout properties & reduce heavy logging 

---

Cargo.lock
components/apps/Cargo.toml
components/apps/src/lib.rs
components/utils/Cargo.toml
components/utils/src/constants.rs
components/utils/src/lib.rs
runners/embedded/Cargo.toml
runners/embedded/build.rs
runners/embedded/src/bin/app-nrf.rs
runners/embedded/src/lib.rs
runners/embedded/src/soc_lpc55/init.rs
runners/embedded/src/soc_lpc55/mod.rs
runners/embedded/src/soc_lpc55/nfc.rs
runners/embedded/src/types.rs
runners/usbip/src/main.rs

This patch adds the full version string and the init status to the admin app.  The init status is set:
- if we fail to communicate with the NFC chip
- if we can’t mount the internal or external flash and have to re-format it
- if a data migration fails

Add full version and init status to admin app

---

Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/lib.rs
runners/embedded/Cargo.toml
runners/usbip/src/main.rs

- Use apdu-dispatch 0.1.2 instead of fork
- Use usbd-ccid 0.2.0 instead of Git dependency
- Bump oath-authenticator
- Bump trussed-usbip

Bump dependencies

---

components/apps/src/lib.rs
runners/embedded/src/bin/app-nrf.rs
runners/embedded/src/soc_lpc55/init.rs
runners/embedded/src/types.rs
runners/usbip/src/main.rs

This patch introduces a custom Dispatch implementation in the apps crate
and makes use of it in the embedded and usbip runners.  This is a
preparation for adding custom backends to the firmware.

 Use custom dispatch 

---

Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/lib.rs

This alpha release contains bug fixes and compatibility improvements for opcard and oath-authenticator.
To do:

Release v1.2.2-alpha.20230224

---

Cargo.lock
Cargo.toml

This patch replaces upstream ctap-types with a fork that improves compatibility when deserializing COSE keys.

Fork ctap-types

---

Cargo.lock
components/apps/Cargo.toml
components/apps/src/lib.rs
runners/embedded/src/lib.rs

This patch extends the status reported by the admin app with the available blocks on the internal and external filesystem at boot time.
Requires: https://github.com/Nitrokey/admin-app/pull/3

admin-app: Add available blocks to status

---

ssh/troubles/.gitignore
utils/nrf-bootloader/.gitignore
utils/nrf-builder/.gitignore

This patch adds three gitignore files so that executing the examples and builders in this repository does not create untracked files.

Extend gitignore

---

Cargo.lock
components/lfs-backup/Cargo.toml
components/lfs-backup/src/lfs_backup.rs
components/lfs-backup/src/lib.rs
components/lfs-backup/src/tests.rs
runners/embedded/Cargo.toml
runners/embedded/src/flash.rs
runners/embedded/src/lib.rs
runners/embedded/src/soc_nrf52840/flash.rs
runners/embedded/src/soc_nrf52840/migrations/ftl_journal/backends.rs
runners/embedded/src/soc_nrf52840/migrations/ftl_journal/ifs_flash_old.rs
runners/embedded/src/soc_nrf52840/migrations/ftl_journal/mod.rs
runners/embedded/src/soc_nrf52840/migrations/mod.rs
runners/embedded/src/soc_nrf52840/mod.rs
utils/nrf-builder/Makefile.test-ftl-migration

Improving the power-loss filesystem-corruption resistance for nRF-based Nitrokey 3 Mini. 
This essentially consists of 3 parts:
* `fsbackup.rs` introduces a generic littlefs2 to blob and back mechanism (backup & restore)
* `soc_nrf52840/flash.rs` introduces the journaling and littlefs2 recovering functionality 
* the actual migration from the old littlefs2 filesystem layout to the new (journaled) layout
Initial draft still WIP, at least the following parts are missing:

nRF: journaling IFS for better power loss resistance & migration mechanism

---

Cargo.lock
runners/embedded/Makefile
runners/embedded/src/lib.rs
rust-toolchain.toml

This patch updates the default Rust version from 1.65 to 1.68.  As support for custom allocators has been stabilized, we can now also use it for the alpha (instead of nightly).  We just have to drop the custom alloc error handler (default: panic) and update the linked_list_allocator dependency.

Use Rust 1.68 for stable and alpha

---

docs/lpc55-quickstart.md
utils/lpc55-builder/Makefile
utils/lpc55-builder/config/keystore.toml

This patch adds the provision-release target to the lpc55-builder Makefile that provisions the keystore and enables the encrypted storage using the PRINCE peripheral.  This setup is closer to production than our develop setup without storage encryption.  The advantage of the develop setup is that it is easy to read out the internal flash for debugging.

lpc55-builder: Add provision-release target

---

runners/embedded/src/soc_lpc55/mod.rs

This patch adds log-rtt to the list of features that enable the delog initialization.

lpc55: Enable delog for log-rtt feature

---

runners/embedded/Cargo.toml
runners/embedded/src/bin/app-nrf.rs
runners/embedded/src/soc_nrf52840/migrations/ftl_journal/mod.rs
runners/embedded/src/soc_nrf52840/types.rs

NRF: use SPIM instead of QSPI for external storage

---

CHANGELOG.md
runners/usbip/src/main.rs
runners/usbip/src/store.rs

Previously, we always used RAM for the EFS in the usbip runner.  This patch adds an --efs option to use a file instead.  The helper types introduced by this patch should eventually be merged into trussed::virt.
https://github.com/Nitrokey/nitrokey-3-firmware/issues/219

usbip: Support EFS on the filesystem

---

docs/ctaphid-commands.md

This patch adds the new global command 0x72 for admin-app to the CTAPHID command list, see <https://github.com/Nitrokey/admin-app/pull/1>.

docs: Update CTAPHID command list

---

docs/identifiers.md

This patch adds the project names and part numbers for all devices that have been produced previously or are currently in production to the identifiers documentation.

Add project names and part numbers

---

Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/dispatch.rs

This patch adds the RSA backend that will be necessary for the PIV application and for the updated OpenPGP smartcard.
The rsa backend is added behind the `rsa` feature flag, which is currently not enabled for anything.

Add rsa backend

---

Cargo.lock
Cargo.toml
runners/embedded/src/ui.rs

This patch adds two custom status variants that can be used for reverse HOTP.  They cannot be overwritten by other status changes

Add custom status variants for reverse HOTP

---

.gitlab-ci.yml

This patch separates the jobs executed for normal builds (push, nightly) and for release builds (web):  For normal builds, only the source code is checked but no binaries are built.  For release builds, only the required binaries are built.  This should speed up the builds and reduce confusion between stable and alpha images.
As part of these changes, this patch also:
- adds a check that releases are always created from a proper tag,
- drops the zip files for the binaries,
- changes the naming so that the binaries are always called firmware and provisioner (not: alpha), and
- enables the sparse protocol for the crates.io registry.
This reduces the time required for regular builds from ~ 6:30 min to ~ 3:30 min.  The time for release builds should decrease even more.  See pipelines 19413 …

ci: Separate normal and release jobs

---

.gitlab-ci.yml
Dockerfile

This patch adds additional checks to scheduled CI jobs:
- All binaries are built to catch errors during the linking stage that are not detected by the regular CI.
- The job is executed with the latest stable and the latest nightly Rust versions instead of the pinned version to find potential compatibility problems early.
Fixes: https://github.com/Nitrokey/nitrokey-3-firmware/issues/241

Extend nightly CI checks

---

CHANGELOG.md
Cargo.lock
components/apps/Cargo.toml
components/apps/src/lib.rs

This patch introduces a limit of ten resident credentials, see: https://github.com/Nitrokey/nitrokey-3-firmware/issues/207
This PR depends on:
- https://github.com/Nitrokey/fido-authenticator/pull/12

fido-authenticator: Limit resident credentials

---

CHANGELOG.md
components/apps/Cargo.toml
components/apps/src/lib.rs
runners/embedded/Cargo.toml

This patch adds opcard to the default applications.  This also means
that we have to enable alloc per default for RSA support.
Fixes https://github.com/Nitrokey/nitrokey-3-firmware/issues/100

Stabilize opcard

---

Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/lib.rs

Update Secrets App to v0.11
- Rename to Secrets App / secrets-app / secrets_app
- Add credentials limit, and set to 50
- Send serial number
- Change dependency to use `0.11.0-rc1`
To discuss:

Update Secrets App to v0.11

---

utils/lpc55-builder/Makefile

related to https://github.com/Nitrokey/nitrokey-3-firmware/issues/187#issuecomment-1484869788
just an idea, if it doesn't fit, I'll close this but so far it works with this patch

wait 5 more seconds for dev to show up during provision-develop

---

Cargo.lock
Cargo.toml
components/nfc-device/Cargo.toml
components/nfc-device/src/iso14443.rs
runners/embedded/Cargo.toml
runners/embedded/src/lib.rs
runners/embedded/src/types.rs
runners/embedded/src/types/usbnfc.rs

Dependant Open PRs:
- pc-usbip-runner:
- https://github.com/trussed-dev/pc-usbip-runner/pull/25
- usbd-ccid:
- https://github.com/trussed-dev/usbd-ccid/pull/10
- apdu-dispatch:
- https://github.com/trussed-dev/apdu-dispatch/pull/16
- usbd-ctaphid:
- https://github.com/trussed-dev/usbd-ctaphid/pull/4
- ctaphid-dispatch:
- https://github.com/trussed-dev/ctaphid-dispatch/pull/3

Bump all dependencies to their interchange 0.3.0 versions

---

Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/lib.rs
components/provisioner-app/src/ctaphid.rs
runners/embedded/Cargo.toml
runners/embedded/src/lib.rs
runners/embedded/src/soc_nrf52840/trussed_ui.rs
runners/embedded/src/types.rs
runners/embedded/src/types/usbnfc.rs

- https://github.com/trussed-dev/trussed/pull/125
Similar work will be needed for the CCID stack too, but is not as urgent, so to simplify we just do CTAPHID  
- https://github.com/trussed-dev/ctaphid-dispatch/pull/4
- https://github.com/trussed-dev/usbd-ctaphid/pull/5
There is a breaking change. Since the CoreContext holds a reference to the interrupt flag, it can't be created as easily as before, and therefore the Fliestore need to take a `ClientId` rather than a CoreContext to be created.
- https://github.com/trussed-dev/trussed-auth/pull/35
- https://github.com/Nitrokey/trussed-staging/pull/7
- https://github.com/Nitrokey/admin-app/pull/4
- https://github.com/Nitrokey/fido-authenticator/pull/15
- https://github.com/Nitrokey/trussed-secrets-app/pull/72
- …

Add support for FIDO request cancellation

---

utils/nrf-bootloader/Makefile
utils/nrf-builder/Makefile
utils/nrf-debugging/binary.elf
utils/nrf-debugging/gdb-stack.cmds
utils/nrf-debugging/graph_stack.py

This PR concerns debug tooling for NRF52 hardware:
- select bootloader by name, to make sure other device is not connected to during flashing (evaluated lazily at the call moment)
- add simple tracing and graphing script for stack memory diagnostics
Connected: https://github.com/Nitrokey/nitrokey-3-firmware/pull/118
Further work ideas:
- ideally gdb would step out automatically, while being in the Rust core libraries (e.g. memcpy) - should be achievable with Python.
Example chart:

NRF52 debug tools update

---

Cargo.toml

The required patch is merged to upstream, but it was not released by tag, nor released on crates.io,
hence the tagged release use on fork.
This is a Secrets App dependency. The patch contains stability corrections (returns error, instead of panicking on unimplemented behavior).
Connected:
- https://lib.rs/crates/flexiber
- https://github.com/Nitrokey/flexiber
- https://github.com/nickray/flexiber

Update flexiber to the forked version

---

Cargo.lock
Cargo.toml
utils/nrf-builder/Makefile

Tested on NK3 AM, with touch button accepting all automatically (`EXTRA_FEATURES=no-buttons`):
- [report-pynitrokey-v0.4.38-20-g2c57d06_secrets-v0.12-rc1_nk3-v1.5.0-test.20230613-26-gda3607c.html.gz](https://github.com/Nitrokey/nitrokey-3-firmware/files/11949296/report-pynitrokey-v0.4.38-20-g2c57d06_secrets-v0.12-rc1_nk3-v1.5.0-test.20230613-26-gda3607c.html.gz)
Load tests included.
Versions:
- pynitrokey: v0.4.38-20-g2c57d06
- secrets: v0.12-rc1
- nk3: v1.5.0-test.20230613-26-gda3607c
With this PR comes also:
- Flexiber update to 1.1
- fix for the TTY selection by id
Fixes: https://github.com/Nitrokey/nitrokey-3-firmware/issues/303
Fixes:
- https://github.com/Nitrokey/nitrokey-3-firmware/issues/300
- https://github.com/Nitrokey/nitrokey-3-firmware/issues/296
-------
Edit: re-released …

Update secrets-app to v0.12

---

Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/dispatch.rs
components/apps/src/lib.rs

Add Nitrokey WebCrypt application
For now to be available only in the testing releases.
Fixes https://github.com/Nitrokey/nitrokey-3-firmware/issues/273
Connected: https://github.com/Nitrokey/nitrokey-webcrypt-rust/issues/4
Can be tested against:
- https://webcrypt.nitrokey.com/ (tested with Chrome; `Reset and Login -> sign and decrypt`)
- `v0.2-28-g610f42f` / https://github.com/Nitrokey/nitrokey-webcrypt-tests/tree/devel (`make FIDO2`)
Built with:
```
$  make flash-develop EXTRA_FEATURES=apps/test,no-buttons
```
-----------
Edit: NK3 AM test results:
- [report.zip](https://github.com/Nitrokey/nitrokey-3-firmware/files/11918773/report.zip)

Add Nitrokey WebCrypt

---

Cargo.toml
runners/embedded/Makefile

Always use `LTO=fat`, unless NRF52/test is built - then use `LTO=thin`

Revert LTO change for all variants, except for the NRF52/test

---

runners/embedded/Makefile
runners/embedded/create_cfg.sh

Cargo recompiles (and reruns the build.rs) if the cfg.toml file has been modified Previously all calls to `make` rewrote this file and thus caused unneccessary recompilation. This patch adds a check that the contents of the file should actually be modified before rewriting it.

Fix embedded runner always recompiling

---

Cargo.lock
Cargo.toml
runners/usbip/Cargo.toml
runners/usbip/src/main.rs

This patch adds a setting for the usbip runner, user presence.  The default and current behavior is to always accept user presence checks. Alternatively, they can always be rejected or answered interactively with a prompt.  To make this work, we need to update the trussed-usbip crate to support keepalive messages.

usbip: Add interactive user presence check

---

runners/embedded/src/soc_nrf52840/trussed_ui.rs

This correctly positions the `set_waiting()` calls as suggested inside the issue.
Tested with the google-ctap2-test-suite + nk3am. It now properly outputs:
```
Please touch your security key!
```

nrf: move set_waiting in button handling

---

runners/usbip/Makefile

This patch adds an attach target, copied from the trussed-usbip repository, to the Makefile for the usbip runner.  This target loads the kernel module required for usbip and activates the usbip device.
Fixes: https://github.com/Nitrokey/nitrokey-3-firmware/issues/322

usbip: Add attach target to Makefile

---

components/apps/Cargo.toml
components/apps/src/lib.rs
docs/usbip.md
runners/usbip/Cargo.toml

This patch adds a ccid feature to the usbip runner for the CCID transport and disables it by default.  This is to avoid accidentally triggering the kernel bug described in this issue:
https://github.com/Nitrokey/nitrokey-3-firmware/issues/261
Fixes: https://github.com/Nitrokey/nitrokey-3-firmware/issues/325

usbip: Disable CCID by default

---

Cargo.toml

Partially fix #328 . Registration still fails with discourse but now it gets to a internal server error instead of a failed CBOR deserialization.

Use updated ctap-types and fido-authenticator for better compatibility with Firefox

---

Cargo.lock
rust-toolchain.toml

This pulls in https://github.com/rust-lang/rust/pull/111364 (released in 1.71.0) that should fix the Dwarf errors we encountered when running the firmware with gdb on lpc55.  This also means we now use the sparse cargo index per default which should improve build times.
Fixes: https://github.com/Nitrokey/nitrokey-3-firmware/issues/119

Bump Rust version to 1.72.0

---

.gitlab-ci.yml
Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/lib.rs
runners/embedded/src/lib.rs
runners/embedded/src/types.rs
runners/usbip/src/main.rs

This patch adds a basic config mechanism using the admin app.  The configuration is loaded and applied during initialization.  The admin app now has a special role, is constructed first and can no longer be disabled.  Other applications can receive a reference to the configuration loaded by the admin app.
To avoid overwriting configuration values for apps that are not enabled in the current firmware, the components of the Config struct are not feature-gated.  It could be simplified by using a derive macro but that seems overcomplicated for a first implementation.
The first use case for the config mechanism is enabling or disabling skipping the FIDO2 user presence check directly after boot.

Add basic config mechanism for fido2

---

.gitlab-ci.yml

this moves the `.gitlab-ci.xml` include into our internal git(lab) instance

ci: move common-jobs

---

CHANGELOG.md
Cargo.lock
Cargo.toml
Makefile
components/apps/Cargo.toml
components/apps/src/dispatch.rs
components/apps/src/lib.rs
runners/embedded/Cargo.toml
runners/embedded/Makefile
runners/embedded/src/bin/app-nrf.rs
runners/embedded/src/lib.rs
runners/embedded/src/soc_lpc55/init.rs
runners/embedded/src/soc_lpc55/mod.rs
runners/embedded/src/soc_lpc55/types.rs
runners/embedded/src/soc_nrf52840/types.rs
runners/embedded/src/types.rs
runners/usbip/src/main.rs
runners/usbip/walk.sh
utils/nrf-debugging/binary

This PR adds a test for the admin app in the SE050.
Linked nitropy PR: https://github.com/Nitrokey/pynitrokey/pull/423
Linked admin-app PR: https://github.com/Nitrokey/admin-app/pull/5

Admin app se050 test

---

components/apps/src/dispatch.rs

Instead of
```
<*Backend as ExtensionImpl<*Extension>>::extension_request_serialized
```
we can just write
```
ExtensionImpl::<*Extension>::extension_request_serialized
```

Simplify extension request dispatch

---

Cargo.lock
Cargo.toml

Tested with https://github.com/Nitrokey/nitrokey-3-tests/commit/a70cad378ef6ae07c92641a4bc809fec32f63e10:
- ✔️ usbip
- ✔️ usbip upgrade from f3b5aad32b654965859db1330c921bfd6710c053
Tested with https://github.com/Nitrokey/nitrokey-3-tests/pull/31/commits/635fd6e6f8a210b3ce3944552eb0f79e7a55cdef:
- ✔️ lpc55

Release v1.5.0-test.20231026

---

.gitlab-ci.yml

Currently, the release CI cannot be started:
>  'hardware-tests' job needs 'build-firmware-for-tests' job, but
>  'build-firmware-for-tests' is not in any previous stage
This patch attempts to fix the problem by activating the build-firmware-for-tests jobs for pipelines triggered from the web interface.

Add CI_PIPELINE_SOURCE web to build-firmware-for-tests

---

.gitlab-ci.yml

This is a follow-up to https://github.com/Nitrokey/nitrokey-3-firmware/pull/363:
The build-firmware-for-tests job could potentially mess up the binaries generated for the release, so it is safer to drop the hardware tests from the release CI, especially as they do not work yet.

Disable hardware tests for releases

---

Cargo.lock
Cargo.toml

This patch updates fido-authenticator and ctap-types to fix an incompatibility with the Chromium credential management.
Depends on:
- https://github.com/Nitrokey/ctap-types/pull/13
- https://github.com/Nitrokey/fido-authenticator/pull/39

Update fido-authenticator, ctap-types, webcrypt

---

.gitlab-ci.yml

This removes the nightly files upload and docker rebuild to re-activate the scheduled pipeline...

ci: remove upload and container build from scheduled

---

Cargo.lock
Cargo.toml
components/utils/Cargo.toml
components/utils/build.rs
components/utils/src/constants.rs
docs/maintenance.md
runners/embedded/Cargo.toml
runners/embedded/src/lib.rs

This patch changes the way we handle versioning:  The crate version defined in the root Cargo.toml is now only changed for stable releases or release candidates.  The test suffix is automatically added if the test feature is enabled.  Additionally, build metadata with the Git commit and worktree status is added to the version string.  Finally, there are additional checks to make sure that tag names match the computed version.
Fixes: https://github.com/Nitrokey/nitrokey-3-firmware/issues/339
All required steps are added to a build script.  It would be possible to move some or all of them into the Makefile, but this makes sure that we get consistent results independent of the build method, it is easier to implement all checks and for me it did not cause any unnecessary rebuilds.
Still …

Refactor versioning

---

CHANGELOG.md
runners/embedded/src/bin/app-nrf.rs
runners/embedded/src/lib.rs
runners/embedded/src/soc_lpc55/init.rs
runners/embedded/src/soc_lpc55/mod.rs

This patch splits the NFC and USB initialization and moves the USB initialization to the end of the initialization process on the lpc55. This makes sure that we can respond to all USB requests as the poll task is started directly after the init process.
Previously, we initialized the USB interface at the beginning of the process so that we could not respond to requests until the end of the init process.  This could potentially mean that the device would lose the initial GET DESCRIPTOR request sent by the Linux kernel, causing a delay of typically 5 s after connecting the device.
Fixes: https://github.com/Nitrokey/nitrokey-3-firmware/issues/302

lpc55: Move USB initialization to end

---

CHANGELOG.md
Cargo.lock
Cargo.toml
components/ndef-app/src/ndef.rs
components/provisioner-app/src/apdu.rs

Depends on:
- https://github.com/Nitrokey/nitrokey-websmartcard-rust/pull/11
- https://github.com/Nitrokey/trussed-secrets-app/pull/104
- https://github.com/Nitrokey/piv-authenticator/pull/39
- https://github.com/Nitrokey/opcard-rs/pull/184
- https://github.com/Nitrokey/admin-app/pull/14
- https://github.com/Nitrokey/fido-authenticator/pull/40

Prepare release 1.6.0-rc.1

---

Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/dispatch.rs
components/apps/src/lib.rs

This PR adds full device factory reset functionality
Depends on
- https://github.com/Nitrokey/admin-app/pull/15
- https://github.com/trussed-dev/littlefs2/pull/47
- https://github.com/Nitrokey/opcard-rs/pull/188

Factory reset

---

.gitlab-ci.yml
CHANGELOG.md
Cargo.lock
Cargo.toml

* Version bump to `v1.6.0`
* Update changelog (no changes since v1.6.0-rc.1)
waits for #387 merge, then rebase, then let's go

Prepare release 1.6.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/lib.rs
runners/embedded/src/lib.rs
runners/embedded/src/types.rs
runners/usbip/src/main.rs

This patch updates fido-authenticator to add support for the largeBlobKey extension and the largeBlobs command.  See the fido-authenticator PR for more information:
- https://github.com/Nitrokey/fido-authenticator/pull/41

fido-authenticator: Add large blobs support

---

CHANGELOG.md
Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/lib.rs
runners/embedded/Cargo.toml
runners/embedded/src/bin/app-nrf.rs
runners/embedded/src/lib.rs
runners/embedded/src/soc_lpc55/init.rs
runners/embedded/src/soc_lpc55/nfc.rs
runners/embedded/src/types.rs

This patch updates the admin-app dependency to report errors when loading the config from IFS during intialization.  It adds a new init status flag CONFIG_ERROR and disables the opcard application if such an error occured to ensure security and stability (as the opcard configuration will determine the backend that is used).

Handle config error in admin app

---

Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/dispatch.rs
components/apps/src/lib.rs
runners/embedded/Cargo.toml
runners/embedded/src/soc_lpc55/types.rs

Depends on
- https://github.com/trussed-dev/trussed/pull/141
- https://github.com/Nitrokey/opcard-rs/pull/187

Use feature-complete SE050 backend

---

runners/embedded/Cargo.toml
runners/embedded/Makefile
runners/embedded/src/bin/app-lpc.rs
runners/embedded/src/bin/app-nrf.rs
runners/embedded/src/soc_lpc55/mod.rs
rust-toolchain.toml

This feature fully disables delog, but this makes it a "negative" feature. So it can't be enabled by default and we need to find a way to enable it for production releases

Add no-delog feature

---

Cargo.lock
components/provisioner-app/Cargo.toml
components/provisioner-app/src/lib.rs

I tested the provisioning process and tests reverting 9768fb722af59334d28d71b829b36616e3626f7f, the key generation still works as expected.
This removes the uECC dependency and allows de-duplicating multiple other dependencies.

Provisionner: Move from `nisty` to `p256-cortex-m4` for key generation

---

Cargo.lock
components/provisioner-app/Cargo.toml
components/provisioner-app/src/lib.rs

Remove one more duplicate dependency. Built on top of #405

provisionner-app: Upgrade salty to version 0.3.0

---

CHANGELOG.md

Previously, the changelog for 1.6.0-rc.1 says:
> - Remove challenge response authentication method ([trussed-secrets-app#44][])
Actually, this method was behind a feature flag that was already disabled in previous releases, so it’s not a relevant change for users.  This patch removes the entry.

Update changelog for secrets-app

---

Cargo.lock
components/apps/Cargo.toml

RSA support was put behind a flag for upstream merge but we forgot to enable this flag here

PIV: enable rsa

---

Cargo.lock
Cargo.toml

Built on top of 
- #407 
- https://github.com/trussed-dev/trussed-rsa-backend/pull/8

Update RSA backend

---

Cargo.lock
Cargo.toml

This patch pulls in two dependency updates:
- trussed removes unused syscalls.
- cbor-smol adds an inline-never hint that reduces binary size.

Update trussed, cbor-smol

---

utils/gen-commands-bd/src/main.rs
utils/nrf-builder/Makefile

The nrf-builder util still used the gen-command-bd to determine the versions of the firmware.

Fix nrf-builder version

---

.gitlab-ci.yml

* the HIL repository is bumped to v1.1, which now includes basic tests for secrets and opcard
* nightly upload is disabled for now
* `test` is now also fully built to catch binary-size-issues
should be good to merge once the HIL went through

CI improvements

---

components/apps/src/lib.rs
runners/embedded/src/bin/app-lpc.rs
runners/embedded/src/bin/app-nrf.rs
runners/embedded/src/lib.rs
runners/embedded/src/soc_lpc55/clock_controller.rs
runners/embedded/src/soc_lpc55/init.rs
runners/embedded/src/soc_lpc55/mod.rs
runners/embedded/src/soc_lpc55/types.rs
runners/embedded/src/soc_nrf52840/migrations/ftl_journal/backends.rs
runners/embedded/src/soc_nrf52840/migrations/ftl_journal/mod.rs
runners/embedded/src/soc_nrf52840/mod.rs
runners/embedded/src/soc_nrf52840/types.rs
runners/embedded/src/store.rs
runners/embedded/src/types.rs

This is a follow-up to:
- https://github.com/Nitrokey/nitrokey-3-firmware/pull/412
It makes the store implementation generic over the `Soc` implementation, meaning that we no longer use any `Soc as SocT` typedef constructs and that the library part of the embedded runner is fully generic over the `Soc`.  This also makes the storage initialization much easier to read, partly by moving the Soc-specific code like the NRF52 IFS migration out of the common implementation and into the soc module.
The downside is that the `static mut`s holding the storage components need concrete types and cannot be defined using generics, so they have to be provided by every `Soc` implementation.  I introduced a helper trait and a macro so it is not necessary to manually write the required boilerplate code.
I …

Refactor Soc trait, part II (storage)

---

runners/embedded/Makefile
runners/embedded/src/bin/app-lpc.rs
runners/embedded/src/bin/app-nrf.rs
runners/embedded/src/lib.rs

The automatic activation of the `no-delog` feature introduced in https://github.com/Nitrokey/nitrokey-3-firmware/pull/399 does not work properly because it tries to access the feature variable before it is defined.  This patch simplifies the Makefile by removing unused targets and redundant variables, fixes the feature computation, fixes compilation if the `no-delog` feature is not set and adds a `build-all` target similar to `check-all` etc.

Simplify and fix embedded runner Makefile

---

Makefile

I realized in #431 that `make check` didn't check the nkpk runner.

Make check: add nkpk check

---

Dockerfile
Makefile
components/apps/src/lib.rs
components/boards/src/init.rs
components/boards/src/nk3am.rs
components/boards/src/nk3am/migrations/ftl_journal/backends.rs
components/boards/src/nk3am/migrations/ftl_journal/mod.rs
components/boards/src/nk3xn.rs
components/boards/src/nk3xn/button.rs
components/boards/src/nk3xn/nfc.rs
components/boards/src/nk3xn/prince.rs
components/boards/src/nkpk.rs
components/boards/src/soc/lpc55/clock_controller.rs
components/boards/src/soc/nrf52.rs
components/boards/src/soc/nrf52/flash.rs
components/boards/src/store.rs
components/fm11nc08/src/device.rs
components/lfs-backup/src/lfs_backup.rs
components/ndef-app/src/ndef.rs
components/nfc-device/src/iso14443.rs
components/utils/src/build.rs
runners/embedded/Makefile
runners/embedded/build.rs
runners/embedded/src/bin/app-lpc.rs
runners/embedded/src/nk3xn/init.rs
runners/nkpk/Makefile
runners/nkpk/build.rs
rust-toolchain.toml

Following #438, I realized that `make lint` didn't run clippy. 
I added a clippy pass to `make lint` and fixed the warnings.
Some lints where deny-by-default, but they didn't seem to be the cause of any bug, and some were false positives due to our may possible `cfg` combinations.
It's very well possible that there are also some lints that affect features that are off by default and are not fixed here.

Make lint: add clippy lints and fix them

---

utils/nrf-builder/Makefile

Missed as part of https://github.com/Nitrokey/nitrokey-3-firmware/pull/448

Fix remaining NK3_FW_DIR in makefile depenencies.

---

components/boards/src/nk3am/ui.rs
components/boards/src/nk3xn/button.rs
components/boards/src/ui.rs
components/boards/src/ui/buttons.rs

This fixes a warning due to unused code.

Remove clock from UserPresence::check_user_presence

---

CHANGELOG.md
Cargo.lock
Cargo.toml

We cannot actually use trussed-dev main because there was a bump in version number making the patch incompatible with all the dependencies

Update apdu-dispatch to fix GPG being locked when factory-reset is interrupted

---

components/utils/src/build.rs
runners/embedded/build.rs
runners/nkpk/build.rs
runners/usbip/build.rs

With this patch, we ignore tags when checking the version string in the CI unless we are currently building the relevant project for the runner. This means that the NKPK build does no longer fail the CI when running on a release tag for the NK3 firmware.

Only validate tags for the relevant project in CI

---

.gitignore
.gitlab-ci.yml
Dockerfile
Makefile
repometrics.toml

This is a first step to add metrics to this repository.  It uses [repometrics](https://github.com/Nitrokey/repometrics) to generate a `metrics.toml` file that lists the file size of the stable and test binaries of nk3am, nk3xn and nkpk.  Of course this should be expanded in the future to include additional metrics.  The `metrics.toml` file is stored as a Gitlab artifact, so it will be possible to compare the metrics of a PR against the current main once this is merged.
Currently, the `metrics.toml` file is subject to the regular artifact expiration rules.  I would vote for not expiring it because its size is less than 1 kB and it can potentially be useful in the future to be able to analyze changes over time.
This PR also combines the firmware compilation into one step so that cached …

Add basic file size metrics

---

.gitlab-ci.yml
Dockerfile
repometrics.toml

Previously, we added some basic metrics to the CI.  This patch adds a comparison with the branch base to the CI output.  It also changes the expiry settings so that the metrics are always kept as artifacts.

Print metrics difference in CI

---

Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/dispatch.rs

This PR adapts to these changes that separate Trussed backends and extensions:
- https://github.com/Nitrokey/nitrokey-websmartcard-rust/pull/16
- https://github.com/trussed-dev/trussed-staging/pull/19
- https://github.com/Nitrokey/trussed-se050-backend/pull/13
Also depends on updated applications:
- https://github.com/Nitrokey/admin-app/pull/22
- https://github.com/Nitrokey/fido-authenticator/pull/72
- https://github.com/Nitrokey/opcard-rs/pull/199
- https://github.com/trussed-dev/piv-authenticator/pull/10
- https://github.com/Nitrokey/nitrokey-websmartcard-rust/pull/18

Use extension crates instead of backends

---

utils/nix/.gitignore
utils/nix/nrf-command-line-tools/default.nix

nrf-command-line-tools (nrfjprog) are not available in nixpkgs so this patch adds a simpe derivation to the repository for easy installation.

nix: Add nrf-command-line-tools derivation

---

Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/dispatch.rs
components/apps/src/lib.rs

This patch updates fido-authenticator and trussed-hkdf to use the HkdfExtension provided by trussed-staging, getting rid of the separate trussed-hkdf backend.

Use trussed-staging to provide hkdf extension

---

components/boards/src/lib.rs

There is nothing unsafe done by the handler itself. This fixes a lint

handle_hard_fault: make safe

---

Cargo.lock
Cargo.toml

flexiber v0.1.1 has been released and contains all changes from our fork:
https://github.com/Nitrokey/flexiber/releases/tag/0.1.1.nitrokey
```
$ git describe --contains 0.1.1.nitrokey --exclude 0.1.1.nitrokey
0.1.1~2^2
```

Use upstream flexiber

---

.gitlab-ci.yml
Cargo.lock
Cargo.toml
Dockerfile
runners/embedded/Cargo.toml
runners/embedded/Makefile

This ensures that panicking can be optimized out fully.
Panicking is now caught in a HardFault handler instead.
This is only enabled for LPC55 test releases. Other build configuration will use the  stable rust toolchain.
This needs a workaround for a linker error where the intrinsics used by littlefs are not found by the linker, so it disables use of intrinsics in littlefs when compiling std. See https://github.com/trussed-dev/littlefs2-sys/pull/12

Use the nightly build-std option to compile std with panic_immediate_abort

---

Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/dispatch.rs
components/apps/src/lib.rs
components/apps/src/migrations.rs

I'm not sure this should be merged before the FIDO2 certification is done.
Depends on:
- https://github.com/trussed-dev/trussed/pull/151
- https://github.com/trussed-dev/trussed/pull/150
- ~~https://github.com/nickray/cbor-smol/pull/8~~
Replaced by: 
- https://github.com/Nitrokey/cbor-smol/pull/2
- https://github.com/Nitrokey/admin-app/pull/23
- ~~https://github.com/Nitrokey/fido-authenticator/pull/55~~
- https://github.com/trussed-dev/trussed-auth/pull/39
- https://github.com/Nitrokey/trussed-se050-backend/pull/16
- https://github.com/Nitrokey/trussed-secrets-app/pull/109
- https://github.com/Nitrokey/opcard-rs/pull/201
- https://github.com/Nitrokey/piv-authenticator/pull/48

Implement optimization migrations

---

Cargo.lock
Cargo.toml

Depends on
- https://github.com/Nitrokey/trussed-se050-backend/pull/20
- https://github.com/Nitrokey/se05x/pull/5

Improve se050 constants inlining

---

.gitlab-ci.yml
CHANGELOG.md
Cargo.lock
Cargo.toml

This release adds SE050 support to opcard, updates fido-authenticator to support CTAP 2.1 and introduces app and device factory reset.

Release v1.7.0

---

utils/fido2-mds/requirements.txt

Fixes: https://github.com/Nitrokey/nitrokey-3-firmware/security/dependabot/9

fido2-mds: Update dependencies

---

components/boards/src/init.rs
components/boards/src/lib.rs
components/boards/src/soc.rs
components/boards/src/soc/lpc55.rs
components/boards/src/soc/nrf52.rs
runners/embedded/src/bin/app-nrf.rs
runners/embedded/src/nk3xn/init.rs
runners/nkpk/src/main.rs

This patch removes the static mut device UUID.  This has multiple benefits:  It removes some unsafe code, it makes the initialization order explicit and it makes the code compatible with Rust edition 2024.

Remove static device UUID

---

.gitlab-ci.yml

fixes:
fix openpgp-card-tools to version 0.9.5
ignore pipenv-rm errors

update nitrokey-hardware-test to v1.2.4

---

components/boards/src/soc/nrf52.rs

Fixes: https://github.com/Nitrokey/nitrokey-3-firmware/issues/498

boards: Fix device UUID logging for nrf52

---

.gitlab-ci.yml

Changes nkpk tests to run on a real nkpk instead of a nk3am

hil: update to v1.2.5

---

utils/fido2-mds/Makefile
utils/fido2-mds/generate-mds.py
utils/fido2-mds/metadata/v3/metadata-nk3am-v3.json
utils/fido2-mds/metadata/v3/metadata-nk3am-v3.test.json
utils/fido2-mds/metadata/v3/metadata-nk3xn-v3.json
utils/fido2-mds/metadata/v3/metadata-nk3xn-v3.test.json
utils/fido2-mds/metadata/v4/metadata-nk3am-v4.json
utils/fido2-mds/metadata/v4/metadata-nk3am-v4.test.json
utils/fido2-mds/metadata/v4/metadata-nk3xn-v4.json
utils/fido2-mds/metadata/v4/metadata-nk3xn-v4.test.json

Add the missing v3 metadata with the updated attestation certificate and a new v4 metadata that explicitly sets the claimed crypto strength.

Update FIDO2 metadata statement

---

CHANGELOG.md
Cargo.lock
Cargo.toml

This patch updates fido-authenticator to v0.1.1-nitrokey.15 to add support for scoped PIN tokens when enumerating credentials.  This fixes an incompatibility with libfido2, affecting ssh-agent.
Fixes: https://github.com/Nitrokey/nitrokey-3-firmware/issues/496

Update fido-authenticator to v0.1.1-nitrokey.15

---

components/apps/src/lib.rs

We renamed the test feature in the apps crate from test to nk3-test and missed that it was still used for setting the large blobs config.

Fix large blobs config for test release

---

Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/lib.rs

Pending:
- https://github.com/trussed-dev/trussed/pull/167
- https://github.com/Nitrokey/opcard-rs/pull/207
- https://github.com/Nitrokey/trussed-se050-backend/pull/33
Due to binary size constraints the curves are only supported on Opcard with the SE050 enabled.
Brainpool 512 and NIST P521 are disabled pending response from NXP support for the export failure on the SE050.
Currently they are only enabled in test releases.

Support all NK Pro curves

---

Cargo.lock
Cargo.toml

We are now using the released ctap-types 0.3.0

Remove unused ctap-types patch

---

runners/embedded/Makefile
utils/compare-bloat.py

This patch adds a bloat target to the runner makefile that produces a JSON file containing the output of cargo bloat as well as a Python script that can be used to compare two of these JSON files, producing a list of added, removed and changed symbols sorted by the size change.
Example output:
```
$ python3 utils/compare-bloat.py runners/embedded/bloat-test.json runners/embedded/bloat-test2.json
Summary:
old:      runners/embedded/bloat-test.json
new:      runners/embedded/bloat-test2.json
total size:
delta: 260
old:   488928
new:   489188
added:   4
removed: 0
changed: 703
Added (4):
size    name
10      OUTLINED_FUNCTION_1380
8       OUTLINED_FUNCTION_1379
6       OUTLINED_FUNCTION_1378
4       littlefs2_core::path::Path::as_str
Removed (0):
size    name
Changed (703):
delta   old …
```

Add helper script for binary size analysis

---

utils/nix/shell.nix

Including the hash of the rust-toolchain.toml file in the Nix shell configuration leads to additional maintenance effort and does not provide significant benefits as the toolchain file is tracked by version control.

nix: Remove hash for rust-toolchain.toml

---

.gitlab-ci.yml

This patch adds a step to the build-firmware CI job that ensures that the lockfile is up-to-date.  See also:  https://github.com/Nitrokey/nethsm-pkcs11/issues/221

ci: Validate lockfile

---

CHANGELOG.md
Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/lib.rs

Depends on
- https://github.com/Nitrokey/admin-app/pull/29

Add support for listing configs

---

CHANGELOG.md
Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/dispatch.rs
components/apps/src/lib.rs

Depends on 
Waiting for merge before updating the patch section of the cargo.toml.
- https://github.com/trussed-dev/trussed-staging/pull/25
- https://github.com/Nitrokey/trussed-se050-backend/pull/36
- https://github.com/Nitrokey/trussed-se050-backend/pull/37
- https://github.com/Nitrokey/piv-authenticator/pull/57

PIV: use se050 backend and trussed-auth for key wrapping

---

Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/lib.rs

Depends on:
- https://github.com/Nitrokey/admin-app/pull/32
- https://github.com/Nitrokey/fido-authenticator/pull/103
- https://github.com/trussed-dev/trussed/pull/175
- https://github.com/trussed-dev/ctap-types/pull/68
- https://github.com/Nitrokey/trussed-secrets-app/pull/123
- https://github.com/Nitrokey/nitrokey-websmartcard-rust/pull/24
- https://github.com/Nitrokey/trussed-se050-backend/pull/40

Update cbor-smol to v0.5.0

---

components/boards/src/nk3xn/nfc.rs
runners/embedded/src/nk3xn/init.rs

The reconfigure-nfc feature has been removed when refactoring the runner because we’ve never used it.  This patch removes old code referencing the feature (fixing a new compiler warning).

nk3xn: Remove reference to reconfigure-nfc feature

---

Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/dispatch.rs
components/apps/src/lib.rs
components/apps/src/migrations.rs
components/boards/Cargo.toml
components/boards/src/flash.rs
components/boards/src/nk3am/migrations/ftl_journal/ifs_flash_old.rs
components/boards/src/nk3xn/prince.rs
components/boards/src/soc/nrf52/flash.rs
components/boards/src/store.rs
components/lfs-backup/Cargo.toml
components/lfs-backup/src/lfs_backup.rs
components/provisioner-app/Cargo.toml
components/provisioner-app/src/lib.rs
components/utils/Cargo.toml
components/utils/src/storage.rs
runners/embedded/Cargo.toml
runners/embedded/src/nk3xn/init.rs
runners/usbip/Cargo.toml
runners/usbip/src/store.rs

Depends on:
- https://github.com/trussed-dev/littlefs2/pull/85
- https://github.com/trussed-dev/trussed/pull/171
- https://github.com/Nitrokey/admin-app/pull/33
- https://github.com/Nitrokey/fido-authenticator/pull/107
- https://github.com/lpc55/lpc55-hal/pull/69
- https://github.com/Nitrokey/trussed-secrets-app/pull/124
- https://github.com/Nitrokey/nitrokey-websmartcard-rust/pull/25
- https://github.com/Nitrokey/opcard-rs/pull/214
- https://github.com/Nitrokey/piv-authenticator/pull/62
- https://github.com/trussed-dev/trussed-staging/pull/30
- https://github.com/trussed-dev/trussed-auth/pull/47
- https://github.com/Nitrokey/trussed-se050-backend/pull/42

Update littlefs2 to v0.5.0

---

CHANGELOG.md
components/boards/src/store.rs

With this patch, the EFS is only mounted once if it is mountable.  This significantly reduces bootup time by approximately 0.5 s.
Fixes: https://github.com/Nitrokey/nitrokey-3-firmware/issues/440

Mount EFS only once

---

Makefile

These include the debug info, so we can extract them from the CI artifacts.

make binaries: add elf binaries

---

utils/lpc55-builder/Makefile

Previously, we used the JLinkGDBServer binary that links against the outdated Qt4.  This patch replaces it with JLinkGDBServerCLExe that is included in the same bundle to get rid of the EOL Qt4 dependency and to make sure that we always use CLI mode. (JLinkGDBServer sometimes runs in GUI mode and sometimes in CLI mode depending on the exact version and setup.)

lpc55-builder: Use GDB server CLI

---

CHANGELOG.md
Cargo.lock
Cargo.toml

This patch updates fido-authenticator to make sure that the credential ID for credentials generated with older firmware versions does not change, see https://github.com/Nitrokey/fido-authenticator/issues/111.

Update fido-authenticator to ensure credential ID stability and release v1.8.0-rc.2

---

components/boards/src/store.rs
utils/nrf-debugging/walk.py

Can be improved further once https://github.com/trussed-dev/littlefs2/pull/87 is merged.

Simplify VFS initialization

---

Cargo.lock
Cargo.toml
components/apps/src/lib.rs

Deppends on:
- https://github.com/trussed-dev/trussed/pull/176
- https://github.com/Nitrokey/trussed-se050-backend/pull/41
- https://github.com/Nitrokey/opcard-rs/pull/213
Closes https://github.com/Nitrokey/nitrokey-3-firmware/issues/531

Add support for secp256k1

---

Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/lib.rs
components/boards/Cargo.toml
components/boards/src/init.rs
components/boards/src/runtime.rs
components/lfs-backup/Cargo.toml
components/lfs-backup/src/lfs_backup.rs
components/lfs-backup/src/tests.rs
components/provisioner-app/Cargo.toml
components/provisioner-app/src/apdu.rs
components/provisioner-app/src/ctaphid.rs
components/provisioner-app/src/lib.rs
runners/embedded/Cargo.toml
runners/embedded/src/bin/app-lpc.rs
runners/embedded/src/bin/app-nrf.rs
runners/nkpk/Cargo.toml
runners/nkpk/src/main.rs

Depends on:
- https://github.com/trussed-dev/ctaphid-dispatch/pull/11
- https://github.com/trussed-dev/usbd-ctaphid/pull/15
- https://github.com/trussed-dev/trussed-rsa-backend/pull/14
- https://github.com/trussed-dev/ctaphid-dispatch/pull/12
- https://github.com/trussed-dev/trussed-auth/pull/48
- https://github.com/Nitrokey/trussed-se050-backend/pull/44
- https://github.com/Nitrokey/fido-authenticator/pull/115
- https://github.com/Nitrokey/trussed-secrets-app/pull/127
- https://github.com/Nitrokey/piv-authenticator/pull/67
- https://github.com/Nitrokey/admin-app/pull/34
- https://github.com/Nitrokey/opcard-rs/pull/216

Use upstream trussed and trussed-core

---

runners/nkpk/Cargo.toml
runners/nkpk/Makefile
runners/usbip/src/main.rs

The nkpk was not built with the `no-delog` feature like other keys

Fix incorrect and missing feature flags

---

components/boards/src/init.rs
components/boards/src/lib.rs
components/boards/src/nk3am.rs
components/boards/src/nk3xn.rs
components/boards/src/nkpk.rs
components/boards/src/soc/nrf52.rs
components/boards/src/store.rs
runners/embedded/src/bin/app-lpc.rs
runners/embedded/src/bin/app-nrf.rs
runners/embedded/src/lib.rs
runners/embedded/src/nk3xn.rs
runners/embedded/src/nk3xn/init.rs
runners/nkpk/src/main.rs

To avoid unsafe code and fix some clippy lints, we can move static muts into the locals for the init task which also have static lifetime.  This is currently not possible for all statics because some need to be accessed globally.  This patch moves the easy cases into a new Resources struct and adds it to the locals of the init task.

Move some statics into init task

---

.gitlab-ci.yml
components/apps/src/lib.rs
runners/usbip/Cargo.toml

This PR makes sure that the usbip runner is always built in the CI so that linker errors and failed const assertions are properly detected.  Currently, the build fails as some mechanisms are only implemented by the SE050 backend and are not available in the usbip runner.  Instead of failing the compilation, this PR ignores those mechanisms when compiling the usbip runner so that a runtime error is raised when such a mechanism is used.  In the medium term, we should use a backend providing a software implementation of these mechanisms.

Fix usbip runner build

---

Cargo.lock
Cargo.toml
components/boards/src/lib.rs
components/boards/src/nk3am.rs
components/boards/src/soc/nrf52.rs
runners/embedded/src/bin/app-lpc.rs
runners/embedded/src/bin/app-nrf.rs
runners/embedded/src/nk3xn.rs
runners/embedded/src/nk3xn/init.rs
runners/nkpk/src/main.rs

Behaviour is:
After a watchdog reset: restart to bootloader
For the NRF52: Any soft reset after that (for example after an update): restart normally (this is because it is not possible to clear the `RESETREAS` (reset reason), so the watchdog bit is always set after the first time the watchdog is triggered. This means that clearing requires a power cycle.
Watchdog is configured for 15 minutes, to make sure it does not break any operation.
Depends on:
- https://github.com/lpc55/lpc55-hal/pull/76

Configure the watchdog

---

.gitlab-ci.yml

Previously, we had the metrics comparison and comment creation in the after_script part of the metrics job so that a failure in these commands would not cause a CI failure.  As we increasingly rely on the metrics comments and the relevant commands are pretty stable, this patch moves them to the script part so that we will notice failures more easily.

ci: Move metrics comment from after_script to script

---

.gitlab-ci.yml

In https://github.com/Nitrokey/nitrokey-3-firmware/pull/594, we changed the metrics job to fail if the comment cannot be posted.  This causes a CI failure on main as there is no matching PR for the CI run.  This patch adds a condition to only post the comment if the CI runs against a branch other than main.

ci: Only comment metrics on other branches than main

---

Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/lib.rs
components/boards/src/init.rs
components/boards/src/lib.rs
components/boards/src/runtime.rs
runners/embedded/src/bin/app-lpc.rs
runners/embedded/src/bin/app-nrf.rs
runners/embedded/src/nk3xn/init.rs
runners/nkpk/src/main.rs
runners/usbip/Cargo.toml

This patch updates trussed to remove the need for the clients-? feature and manage the endpoints in the runner instead.

Update trussed to remove clients-? features

---

docs/lpc55-quickstart.md
utils/lpc55-builder/Makefile

* remove: `provision-develop` as it's unused
* change order for `provision-release` to have a proper prince behavior during provisioning
The observation (breaking at main) is that the prince registers look like that after applying `keystore.toml` and flashing the provisioner:
```
0x4003501c:	0x00000001
0x4003502c:	0x00000001
0x4003503c:	0x00003fff
```
This is leading to a panic once the provisioner is flashed (since piv was included, so potentially(!) once a given firmware binary size is reached). Once `factory-settings` with some pid:vid are applied, these show the expected values:
```
0x4003501c:	0x00000000
0x4003502c:	0x00000000
0x4003503c:	0x00000000
```
so this PR essentially only pulls the `factory-setting` before flashing the provisioner and the observed panic doesn't occur …

utils/lpc: adapt provisioning for a better prince init

---

.gitlab-ci.yml
Cargo.lock
Cargo.toml
components/apps/src/lib.rs
components/boards/src/store.rs
components/provisioner-app/src/lib.rs
runners/embedded/src/nk3xn/init.rs
runners/usbip/src/main.rs
runners/usbip/src/store.rs

This patch updates trussed to use the simplified Store trait, see:
- https://github.com/trussed-dev/trussed/pull/195
Depends on:
- https://github.com/trussed-dev/trussed-staging/pull/34
- https://github.com/Nitrokey/admin-app/pull/36

Simplify Store implementation

---

.gitlab-ci.yml

The old logic can lead to problems when the job runs for the first time for a commit on main, e. g. after a merge with a merge commit (instead of a fast-forward merge), as the "root" of the branch is equal to the head and there are no cached metrics for the head.
This also reverts the temporary change to ignore errors during comment creation in https://github.com/Nitrokey/nitrokey-3-firmware/pull/600 as the cause should be fixed with this PR.

ci: Only generate metrics comment for other branches than main

---

CHANGELOG.md
Cargo.lock
components/apps/src/lib.rs
components/boards/src/init.rs
components/boards/src/lib.rs
components/boards/src/nk3am.rs
components/boards/src/nk3xn.rs
components/boards/src/nkpk.rs
components/boards/src/store.rs
components/provisioner-app/Cargo.toml
components/provisioner-app/src/apdu.rs
components/provisioner-app/src/ctaphid.rs
components/provisioner-app/src/lib.rs
runners/usbip/src/main.rs

The ReformatFilesystem command in the provisioner app required direct access to the IFS storage.  This is potentially unsound and adds complexity to the store implementation.  To avoid this requirement, this patch removes the command.  Instead a factory reset can be performed via admin-app to clear the filesystems.  If they need to be formatted, a custom firmware should be used that can format the filesystems during the store setup.

provisioner: Remove ReformatFilesystem command

---

Cargo.lock
Cargo.toml
runners/embedded/Cargo.toml
runners/embedded/src/lib.rs
utils/collect-license-info/Cargo.toml
utils/collect-license-info/src/main.rs

cortex-m-alloc has been deprecated.
The new embedded-allocator supports two allocator algorithms.     This PR uses the same as previously. I will make a PR that switches the allocator to see if there is any benefit.
Also bump minimum apdu-dispatch version to ensure https://github.com/trussed-dev/apdu-dispatch/pull/28 is used.
Uses a fork to fix collect-license-info: https://github.com/onur/cargo-license/pull/79

Dependency updates

---

Cargo.lock
Cargo.toml

This PR merges the v1.8.1 tag to ensure a continuous history and updates the version to v1.8.2 as a preparation for the next test release.

Update version to v1.8.2

---

utils/manifest.template.json

This patch replaces the pynitrokey version requirement with a Nitrokey SDK version requirement.  See this PR for more information on the mechanism:
- https://github.com/Nitrokey/nitrokey-sdk-py/pull/65
We also bump the pynitrokey version requirement to make sure that old versions that are not aware of the SDK version requirement reject new updates.
The reason for this new requirement is the support for the migration to the filesystem layout v2, see:
- https://github.com/Nitrokey/nitrokey-sdk-py/pull/67
- https://github.com/Nitrokey/nitrokey-3-firmware/pull/602

Require Nitrokey SDK v0.3.0 in manifest

---

Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/lib.rs
components/boards/Cargo.toml
components/boards/src/init.rs
components/boards/src/runtime.rs
runners/embedded/Cargo.toml
runners/embedded/src/bin/app-lpc.rs
runners/embedded/src/bin/app-nrf.rs
runners/nkpk/Cargo.toml
runners/nkpk/src/main.rs
runners/usbip/Cargo.toml
runners/usbip/src/main.rs

This makes ctaphid generic over the buffer size and synchronizes the buffer sizes between ctaphid-dispatch and usbd-ctaphid.  As the usbd-ctaphid buffer size was only about half the size of the ctaphid-dispatch buffer size, this should lead to a significantly decreased stack usage in ctaphid-dispatch calls.
Depends on:
- https://github.com/trussed-dev/ctaphid-dispatch/pull/16
- https://github.com/trussed-dev/usbd-ctaphid/pull/20
- https://github.com/trussed-dev/pc-usbip-runner/pull/43
ctaphid-dispatch v0.2.0 is still in Cargo.lock because of webcrypt.

Update ctaphid-dispatch to v0.3.0 and usbd-ctaphid to v0.3.0
