.gitlab-ci.yml

Using fixed tags solves Docker-related issues like this one: https://git.dotplex.com/nitrokey/solo2/-/jobs/30531

.gitlab-ci.yml: use fixed tags for all docker images

---

runners/lpc55/CHANGELOG.md
runners/lpc55/Cargo.lock
runners/lpc55/Cargo.toml
runners/lpc55/config/commands.bd

This release fixes some issues with the FIDO authenticator and the admin
application.

Release v1.0.1-rc.1

---

.gitlab-ci.yml

Update the MAIN_BRANCH variable.

CI - change MAIN_BRANCH (nitrokey-main -> main)

---

README.md
docs/troubleshooting.md

This patch adds a troubleshooting guide that provides solutions for
common issues during development.

Add troubleshooting guide

---

CHANGELOG.md
runners/lpc55/config/commands.bd

This release candidate improves compatibility with Windows 10 and with OpenSSH and changes the LED patterns.

Release v1.0.4-rc.3

---

README.md
docs/testing.md

This patch adds documentation on how to install a release candidate.

Document installation of release candidates

---

CHANGELOG.md

This release improves compatibility with Windows 10 and with OpenSSH and
changes the LED patterns.

Release v1.0.4

---

docs/maintenance.md

This patch adds the guidelines for forks that we discussed on Tuesday.

docs/maintenance: Add forking guidelines

---

CHANGELOG.md
runners/embedded/Cargo.lock
runners/embedded/Cargo.toml
runners/lpc55/Cargo.lock
runners/lpc55/Cargo.toml

This release contains various bugfixes and stability improvements.

Release v1.2.0

---

CHANGELOG.md
runners/embedded/Cargo.lock
runners/embedded/Cargo.toml
runners/lpc55/Cargo.lock
runners/lpc55/Cargo.toml

* update versions
* update changelog

Release v1.2.2

---

.gitignore
.gitlab-ci.yml
Cargo.lock
Cargo.toml
Makefile
components/apps/Cargo.toml
components/apps/src/lib.rs
runners/embedded/.gitignore
runners/embedded/Cargo.toml
runners/embedded/Makefile
runners/embedded/build.rs
runners/embedded/src/lib.rs
runners/embedded/src/soc_lpc55/types.rs
runners/embedded/src/soc_nrf52840/types.rs
runners/embedded/src/types.rs
utils/collect-license-info/Cargo.toml
utils/collect-license-info/src/main.rs

This is a preparation for including the usbip runner.

Create workspace and move apps into component

---

Cargo.lock
components/apps/src/lib.rs
components/provisioner-app/Cargo.toml
components/provisioner-app/src/apdu.rs
components/provisioner-app/src/ctaphid.rs
components/provisioner-app/src/lib.rs

This PR adds ctaphid transport to the provisioner app using the 0x71 vendor command.  Tested with usbip.

provisioner-app: Add ctaphid transport

---

.gitlab-ci.yml
Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/lib.rs
docs/maintenance.md
runners/embedded/Cargo.toml
runners/embedded/src/lib.rs
runners/usbip/.gitignore
runners/usbip/Cargo.toml
runners/usbip/src/main.rs
rust-toolchain.toml

This PR adds a usbip runner that simulates a Nitrokey 3 device.
Interfaces:
Apps:
Features:

Add usbip runner

---

docs/index.md
docs/storage.md

Currently not very interesting, but will become more relevant once we add more applications and also use the external flash.

Add storage documentation

---

components/utils/src/storage.rs

fix formatting issue introduced by #153

---

runners/embedded/src/flash.rs
runners/embedded/src/soc_lpc55/init.rs

Instead of panicking if the communication with the EFS fails, we set an
error flag and use RAM as a fallback.
----
This can be simulated by replacing `into_output_high` with `into_output_low` here:
https://github.com/Nitrokey/nitrokey-3-firmware/blob/c728fae23e8d31a6f514e80e0755c5193e402ca9/runners/embedded/src/soc_lpc55/init.rs#L546
@daringer Do we need something similar for NRF52?
Based on https://github.com/Nitrokey/nitrokey-3-firmware/pull/172

embedded/lpc55: Gracefully handle EFS errors

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Needs to wait for #186 and #195

Prepare 1.3.0 RC 1

---

Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/lfs-backup/Cargo.toml
components/provisioner-app/Cargo.toml
components/utils/Cargo.toml
components/utils/src/storage.rs
runners/embedded/Cargo.toml
runners/embedded/src/flash.rs
runners/embedded/src/soc_nrf52840/flash.rs
runners/embedded/src/soc_nrf52840/migrations/ftl_journal/ifs_flash_old.rs
runners/embedded/src/soc_nrf52840/qspiflash.rs
runners/usbip/Cargo.toml
runners/usbip/src/store.rs

Depends on:
- https://github.com/Nitrokey/fido-authenticator/pull/13

Update littlefs2 to 0.4.0

---

Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/lib.rs
runners/embedded/Makefile
runners/embedded/src/ui.rs
utils/lpc55-builder/Makefile
utils/lpc55-builder/scripts/usbwait.sh

Update Secrets App to v0.10
Will be corrected to the proper version after the review and release.
Depends on:
- https://github.com/Nitrokey/trussed-secrets-app/pull/53

Update Secrets App to v0.10

---

docs/lpc55-quickstart.md

since alpha isn't available anymore, change it to test

docs: fix for test firmware

---

docs/identifiers.md

@jans23 Can you please confirm the new IDs?

docs: Add FIDO2 Mini product ID

---

Cargo.lock
Cargo.toml
components/apps/Cargo.toml

This also adds the needed fix to iso7816

Update opcard to 1.1.0

---

Cargo.lock
Cargo.toml

Prepare test release 1.5.0-test.20230605

---

Cargo.lock
Cargo.toml
components/apps/src/lib.rs

Prepare test release v1.5.0-test.20230704

Prepare test release v1.5.0-test.20230704

---

runners/embedded/Makefile

CI: fix artifact copying for the custom profile

CI: fix artifact copying for the custom profile

---

utils/nrf-builder/Makefile

Fix  test certifacte private key name

---

.gitlab-ci.yml

Automatically flash the just built firmware to the hardware, and test for defects.

CI: add hardware test job

---

runners/embedded/Cargo.toml

activate the `se050-test-app` + `se050` inside the `test` feature

add se050-test-app to test target

---

.gitlab-ci.yml

This will also activate status reports from the hardware-tests into github

ci: activate new gh status notification mechanism

---

.gitlab-ci.yml

* various cleanups within `.gitlab-ci.yml`
* `test` is now part of `test` stage and called `software-tests`
* build all necessary firmware binaries for HIL
* remove nightly docker build (to be fixed)

CI / HIL: lpc55 and nrf52 now "fully" working

---

Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/lib.rs

Depends on https://github.com/Nitrokey/admin-app/pull/16

Put factory reset behind the test feature flag

---

runners/usbip/src/store.rs

Previously, the EFS implementation accidentally checked against the size of the IFS and VFS instead of the actual size of the EFS.

usbip: Fix EFS size checks

---

Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/lib.rs
runners/embedded/Cargo.toml
runners/embedded/src/lib.rs
runners/embedded/src/types/usbnfc.rs

Remove the unused serial usb driver

---

Cargo.lock
Cargo.toml

Depends on:
- https://github.com/Nitrokey/nitrokey-3-firmware/pull/414
- https://github.com/trussed-dev/trussed/pull/144
- https://github.com/trussed-dev/trussed-staging/pull/14

Use DynFilesystem implementations

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Use latest piv-authenticator

---

.gitlab-ci.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/dispatch.rs
components/apps/src/lib.rs
components/boards/src/init.rs
components/boards/src/lib.rs
components/boards/src/nk3am.rs
components/boards/src/nk3xn.rs
components/boards/src/nkpk.rs
runners/usbip/src/main.rs

Depends on:
- https://github.com/Nitrokey/admin-app/pull/21

Update fido-authenticator to support CTAP 2.1

---

Cargo.lock
Cargo.toml
components/apps/src/dispatch.rs
components/apps/src/lib.rs
components/boards/src/init.rs
components/boards/src/soc/lpc55.rs

Depends on:
- https://github.com/Nitrokey/trussed-se050-backend/pull/31
- https://github.com/trussed-dev/trussed/pull/165

Configure se050 backend on boot

---

.gitlab-ci.yml

Add command interface
Add full hardware tests (and slow tests) using command
Merge command should work as well

add command interface

---

Cargo.lock
Cargo.toml
components/apps/src/lib.rs

Depends on https://github.com/Nitrokey/admin-app/pull/26

And random generator failure to init status bytes

---

CHANGELOG.md
Cargo.lock
Cargo.toml
components/apps/src/lib.rs

Depends on 
- https://github.com/Nitrokey/trussed-se050-backend/pull/34
- https://github.com/Nitrokey/se05x/pull/16
- https://github.com/Nitrokey/se05x/pull/17

Add support for p521 and brainpool512

---

CHANGELOG.md
components/apps/src/lib.rs

Disable enable piv opcard

---

Dockerfile
runners/embedded/.cargo/config.toml
runners/nkpk/.cargo/config
rust-toolchain.toml

Also bump nightly to the corresponding version based on when it was branched from main.

Bump rust version to latest release

---

.gitlab-ci.yml

see https://github.com/Nitrokey/nitrokey-hardware-test/pull/14

ci/hil: nrf improve programming robustness

---

components/boards/src/nk3xn/prince.rs

This patch moves around the assertions in the PRINCE implementation to make the code more readable and adds a comment describing the way that PRINCE works.

nk3xn: Improve PRINCE readability and documentation

---

Cargo.lock
Cargo.toml

Depends on
- https://github.com/Nitrokey/trussed/pull/46

Fix memory leak of volatile fs caused by empty directories

---

docs/lpc55-quickstart.md
utils/lpc55-builder/70-lpc55.rules

Two small additions I stumbled accross when commissioning my new Nitrokey 3 (Hacker).

Improve hacker setup instructions

---

Cargo.lock
Cargo.toml
components/apps/src/lib.rs
runners/usbip/Cargo.toml
runners/usbip/src/main.rs
runners/usbip/src/store.rs

Depends on:
- https://github.com/trussed-dev/trussed-staging/pull/35
- https://github.com/trussed-dev/pc-usbip-runner/pull/41

Update store implementation for usbip runner

---

Cargo.lock
Cargo.toml
components/apps/src/lib.rs
components/boards/src/lib.rs

Depends on:
- https://github.com/trussed-dev/trussed/pull/162
- https://github.com/Nitrokey/trussed-se050-backend/pull/50

Update Trussed mechanism implementation

---

Cargo.lock
Cargo.toml
components/apps/Cargo.toml
components/apps/src/dispatch.rs
components/apps/src/lib.rs
components/boards/Cargo.toml
components/boards/src/init.rs
components/boards/src/lib.rs
components/boards/src/nk3am.rs
components/boards/src/nk3xn.rs
runners/embedded/Cargo.toml
runners/embedded/src/nk3xn/init.rs

Depends on:
- https://github.com/Nitrokey/trussed-se050-backend/pull/52

Update to se05x 0.2

---

.gitlab-ci.yml
Cargo.lock
Cargo.toml
Makefile
components/apps/src/lib.rs
components/boards/Cargo.toml
components/boards/src/lib.rs
components/boards/src/store.rs
runners/embedded/Cargo.toml

Depends on :
- https://github.com/trussed-dev/littlefs2/pull/103
- https://github.com/trussed-dev/littlefs2-sys/pull/27
- https://github.com/trussed-dev/trussed-staging/pull/36
- https://github.com/trussed-dev/trussed-staging/pull/37

Reformat EFS on factory reset and shrink fs on failure to mount.
